// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvaC6m8jivATcy6JjjjBWH9oOiFB7ohA',
    appId: '1:39609269343:web:d32cb3855cca6ff39d6fea',
    messagingSenderId: '39609269343',
    projectId: 'pertemuan7-76b7f',
    authDomain: 'pertemuan7-76b7f.firebaseapp.com',
    storageBucket: 'pertemuan7-76b7f.appspot.com',
    measurementId: 'G-N6B9HEH9Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90lvXSjljCmqiGop462OIXTiwclyU4e8',
    appId: '1:39609269343:android:b4cd321ac1fdd18c9d6fea',
    messagingSenderId: '39609269343',
    projectId: 'pertemuan7-76b7f',
    storageBucket: 'pertemuan7-76b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgz3M9XzMIk5njpt7K01vJOoyF9SBWng',
    appId: '1:39609269343:ios:bfe87b03324efd609d6fea',
    messagingSenderId: '39609269343',
    projectId: 'pertemuan7-76b7f',
    storageBucket: 'pertemuan7-76b7f.appspot.com',
    iosClientId: '39609269343-m2ru6ha26ha320vr6lbf4ldsvsg93d7a.apps.googleusercontent.com',
    iosBundleId: 'id.ac.bsi.pertemuan7',
  );
}
